env: dev
server:
  port: 5000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/develop?autoReconnect=true&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
  redis:
    host: 127.0.0.1
    port: 6379
